# -*- coding: utf-8 -*-
"""
Node -> constituent gene symbol list, transcribed from Supplementary Table S1
(MASLD_supplementary_npjSBA_TSENG_20260716.docx). 58 molecular nodes.
Used to recompute v10-Mean node-level ratios from bootstrap-resampled pyDESeq2 output.
"""

NODE_GENES = {
    "ACDC": ["ADIPOQ"],
    "adipoR": ["ADIPOR1", "ADIPOR2"],
    "Akt": ["AKT3", "AKT1", "AKT2"],
    "ATF4": ["ATF4"],
    "Bax": ["BAX"],
    "Bim": ["BCL2L11"],
    "Bid": ["BID"],
    "CASP3": ["CASP3"],
    "CASP7": ["CASP7"],
    "CASP8": ["CASP8"],
    "Cdc42": ["CDC42"],
    "C_EBPa": ["CEBPA"],
    "CxIV": ["COX6B2", "COX4I1", "COX5B", "COX6A1", "COX6A2", "COX6B1", "COX6C",
             "COX7A1", "COX7A2", "COX7B", "COX7C", "COX8A", "COX7B2", "COX8C",
             "MT-CO1", "MT-CO2", "MT-CO3", "COX4I2", "COX7A2L", "COX5A"],
    "IL_8": ["CXCL8"],
    "Cytc": ["CYCS"],
    "CYP2E1": ["CYP2E1"],
    "CHOP": ["DDIT3"],
    "PERK": ["EIF2AK3"],
    "eIF2a": ["EIF2S1"],
    "IRE1a": ["ERN1"],
    "Fas": ["FAS"],
    "FasL": ["FASLG"],
    "AP_1": ["FOS", "JUN"],
    "GSK_3": ["GSK3A", "GSK3B"],
    "IKKb": ["IKBKB"],
    "IL_1": ["IL1A", "IL1B"],
    "IL_6": ["IL6"],
    "IL_6R": ["IL6R"],
    "INS": ["INS"],
    "INSR": ["INSR"],
    "IRS_1_2": ["IRS1", "IRS2"],
    "ITCH": ["ITCH"],
    "LEP": ["LEP"],
    "ObR": ["LEPR"],
    "MLK3": ["MAP3K11"],
    "ASK1": ["MAP3K5"],
    "p38": ["MAPK14", "MAPK11", "MAPK13", "MAPK12"],
    "JNK1_2": ["MAPK8", "MAPK9", "MAPK10"],
    "ChREBP": ["MLXIP", "MLXIPL", "MLX"],
    "CxI": ["NDUFC2-KCTD14", "NDUFA11", "NDUFS7", "NDUFA1", "NDUFA2", "NDUFA3",
            "COXFA4", "NDUFA5", "NDUFA6", "NDUFA7", "NDUFA8", "NDUFA9", "NDUFA10",
            "NDUFAB1", "NDUFB1", "NDUFB2", "NDUFB3", "NDUFB4", "NDUFB5", "NDUFB6",
            "NDUFB7", "NDUFB8", "NDUFB9", "NDUFB10", "NDUFC1", "NDUFC2", "NDUFS1",
            "NDUFS2", "NDUFS3", "NDUFV1", "NDUFS4", "NDUFS5", "NDUFS6", "NDUFS8",
            "NDUFV2", "NDUFV3", "NDUFA13", "NDUFB11", "NDUFA12", "COXFA4L2"],
    "NF_kB": ["NFKB1", "RELA"],
    "LXR_a": ["NR1H3"],
    "PI3K": ["P3R3URF-PIK3R3", "PIK3CA", "PIK3CB", "PIK3CD", "PIK3R1", "PIK3R2", "PIK3R3"],
    "L_PK": ["PKLR"],
    "PPAR_a": ["PPARA"],
    "PPAR_g": ["PPARG"],
    "AMPK": ["PRKAG2", "PRKAG3", "PRKAA1", "PRKAA2", "PRKAB1", "PRKAB2", "PRKAG1"],
    "Rac1": ["RAC1"],
    "RXR": ["RXRA"],
    "CxII": ["SDHA", "SDHB", "SDHC", "SDHD"],
    "SOCS3": ["SOCS3"],
    "SREBP_1c": ["SREBF1"],
    "TGF_b1": ["TGFB1"],
    "TNFa": ["TNF"],
    "TNFR1": ["TNFRSF1A"],
    "TRAF2": ["TRAF2"],
    "CxIII": ["UQCR11", "CYC1", "UQCRQ", "UQCR10", "UQCRHL", "MT-CYB", "UQCRB",
              "UQCRC1", "UQCRC2", "UQCRFS1", "UQCRH"],
    "XBP1": ["XBP1"],
}

assert len(NODE_GENES) == 58, f"expected 58 nodes, got {len(NODE_GENES)}"
