#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate Hill-parameter robustness variants of the v10 Mean ODE models.
=======================================================================
Reads the three baseline condition models and writes parameter-tagged
variants for a robustness/sensitivity analysis of the uniform Hill
parameters (Hill coefficient n and half-saturation constant ksp).

Baseline models use hard-coded Hill terms of the form
    (Vmax * X**n) / (ksp**n + X**n)      with Vmax = ksp = n = kcat = 2.0
This script rewrites the literal exponents/half-saturation base only:
    step 1: "2.0**2.0"  (ksp**n)          -> "{ksp}**{n}"
    step 2: remaining "**2.0" (substrate)  -> "**{n}"
Vmax and kcat (the leading "2.0 *" coefficients) are left unchanged.
The in-file PARAMS dict is updated to match, for self-documentation.

Output filename encodes the parameters, e.g.
    ode_model_pydeseq2_NASH_vs_Normal_v10_mean_n1.0_ksp2.0.py
so runs are recorded and reproducible.

Usage (run in the folder containing the three baseline models, or edit
IN_DIR / OUT_DIR):
    python generate_robustness_models.py
"""
import os, re, glob

# ---- configuration -------------------------------------------------
# Auto-resolve repo layout: this script lives in scripts/06_robustness/,
# baseline models live in <repo>/data/models/. Falls back to the script's
# own folder if the models are placed next to it instead.
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT  = os.path.dirname(os.path.dirname(SCRIPT_DIR))
_CANDIDATES = [
    os.path.join(REPO_ROOT, 'data', 'models'),
    SCRIPT_DIR,
]
IN_DIR  = next((d for d in _CANDIDATES
                if os.path.exists(os.path.join(d, 'ode_model_pydeseq2_NASH_vs_Normal_v10_mean.py'))),
               _CANDIDATES[0])
OUT_DIR = os.path.join(IN_DIR, 'robustness_models')

BASE_FILES = [
    'ode_model_pydeseq2_NASH_vs_Normal_v10_mean.py',
    'ode_model_pydeseq2_NAFL_vs_Normal_v10_mean.py',
    'ode_model_pydeseq2_Obese_vs_Normal_v10_mean.py',
]

# Parameter grid: (n, ksp). n-sweep at ksp=2, then ksp-sweep at n=2.
# (2.0, 2.0) is the current primary model, regenerated as a sanity check.
PARAM_GRID = [
    (1.0, 2.0),
    (2.0, 2.0),   # baseline / primary
    (4.0, 2.0),
    (2.0, 1.0),
    (2.0, 4.0),
]

# ---- transform -----------------------------------------------------
def make_variant(src, n, ksp):
    """Return model source with Hill n and ksp rewritten. Vmax/kcat fixed."""
    ksp_s, n_s = f'{ksp:.1f}', f'{n:.1f}'
    # step 1: ksp**n  (the only "2.0**2.0" literal, 140 = #reactions)
    s = src.replace('2.0**2.0', f'{ksp_s}**{n_s}')
    # step 2: remaining substrate exponents "**2.0" -> "**{n}"
    s = s.replace('**2.0', f'**{n_s}')
    # update PARAMS dict for self-documentation (ode uses literals, but keep consistent)
    s = re.sub(r"('ksp'\s*:\s*)2\.0", r"\g<1>" + ksp_s, s, count=1)
    s = re.sub(r"('n'\s*:\s*)2\.0",   r"\g<1>" + n_s,   s, count=1)
    # header tag
    tag = (f"\n# ROBUSTNESS VARIANT  |  Hill n = {n_s}  |  ksp = {ksp_s}  "
           f"|  Vmax = kcat = 2.0 (fixed)\n"
           f"# Generated by generate_robustness_models.py for parameter "
           f"sensitivity analysis.\n")
    s = s.replace('import numpy as np', tag + '\nimport numpy as np', 1)
    return s

def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    n_written = 0
    for base in BASE_FILES:
        path = os.path.join(IN_DIR, base)
        if not os.path.exists(path):
            print(f"  SKIP (not found): {base}"); continue
        with open(path, 'r', encoding='utf-8') as f:
            src = f.read()
        stem = base[:-3]  # strip .py
        for (n, ksp) in PARAM_GRID:
            out_name = f"{stem}_n{n:.1f}_ksp{ksp:.1f}.py"
            with open(os.path.join(OUT_DIR, out_name), 'w', encoding='utf-8') as f:
                f.write(make_variant(src, n, ksp))
            n_written += 1
            print(f"  wrote {out_name}")
    print(f"\nDone. {n_written} variant model files in: {OUT_DIR}")

if __name__ == '__main__':
    main()
