#!/usr/bin/env python3
"""
masld_model.py
==============
Compact, self-contained re-implementation of the v10 Mean hsa04932 ODE model.

The equations are identical to those generated by
interaction_to_ode_keggid_v10_Mean.py (Tseng 2024, N&M 21:65, Eq. 1-2):

  activation   = sum_k kcat * R_k,active * X_inactive^n / (ksp^n + X_inactive^n)
                 (or Vmax * X_inactive^n / (ksp^n + X_inactive^n) if X has no regulator)
                 x prod_j ksp^n / (ksp^n + I_j,active^n)      [structural inhibitors]
  inactivation = Vmax * X_active^n / (ksp^n + X_active^n)

  d X_inactive / dt = -activation + inactivation
  d X_active   / dt =  activation - inactivation

Initial conditions:
  gene node inactive = arithmetic mean of member-gene pyDESeq2 ratios (2^log2FC),
                       NaN -> 1.0, no clipping (uniform policy, see Methods)
  gene node active   = 0
  pathway output P_* inactive = 100, active = 0

Silymarin (Eq. 4): activation rate of the eight target nodes multiplied by k_i.

Unlike the generated model files, this module keeps the right-hand side as a
function so that initial conditions can be overridden programmatically.
"""

import re
import numpy as np
import pandas as pd
from scipy.integrate import odeint

# numpy >= 2.0 renamed trapz -> trapezoid
_trapz = getattr(np, "trapezoid", None) or getattr(np, "trapz")

KSP, N_HILL, KCAT, VMAX = 2.0, 2.0, 2.0, 2.0
P_INIT = 100.0

SILYMARIN_TARGETS = ["CASP3", "CASP7", "CASP8", "CYP2E1",
                     "IL_8", "TNFa", "NF_kB", "TGF_b1"]
CORE_OUTPUTS = ["P_Cell_death", "P_Hepatocyte_injury", "P_Inflammation"]


def sanitize_pathway(name):
    """Pathway-output name -> ODE variable name (same rule as the generator)."""
    s = str(name).replace("TITLE:", "").strip()
    s = re.sub(r"[^a-zA-Z0-9_]", "_", s)
    return re.sub(r"_+", "_", s).strip("_")


class MasldModel:
    """hsa04932 ODE network built from the interaction table."""

    def __init__(self, interactions_file, node_table_file, deg_file):
        # --- node -> ODE variable name and member genes ---
        nnt = pd.read_excel(node_table_file)
        self.var_of = dict(zip(nnt.source_node.astype(str),
                               nnt.ode_variable_name.astype(str)))
        self.genes_of = {}
        for _, row in nnt.iterrows():
            genes = [g.strip() for g in str(row.gene_symbols).split(",")]
            genes = [g for g in genes
                     if g and g != "nan" and not g.startswith("MT-")
                     and not g.startswith("?") and not g.endswith("*")]
            self.genes_of[str(row.source_node)] = genes

        # --- pyDESeq2 ratios per condition ---
        deg = pd.read_excel(deg_file, sheet_name="Merged_3grp")
        self.ratio = {c: dict(zip(deg.Gene.astype(str), deg[f"ratio_{c}"]))
                      for c in ("Obese", "NAFL", "NASH")}

        # --- topology ---
        inter = pd.read_excel(interactions_file)
        self.act, self.inh, self.symbol_of = {}, {}, {}
        genes, pathways = set(), set()
        for _, r in inter.iterrows():
            src, tgt = str(r.source_node), str(r.target_node)
            itype = str(r.interaction_type).lower()
            sub = str(r.subtypes).lower()
            s_var = self.var_of.get(src, src)
            self.symbol_of[s_var] = src
            if tgt.startswith("P_") or itype == "garel":
                t_var = sanitize_pathway(tgt)
                pathways.add(t_var)
                genes.add(s_var)
                is_inh = "inhibition" in sub
            else:
                t_var = self.var_of.get(tgt, tgt)
                self.symbol_of[t_var] = tgt
                genes.update([s_var, t_var])
                is_inh = ("inhibition" in sub) or ("repression" in sub)
            (self.inh if is_inh else self.act).setdefault(t_var, set()).add(s_var)

        self.genes = sorted(genes)
        self.pathways = sorted(pathways)
        self.nodes = self.genes + self.pathways
        self.idx = {n: i for i, n in enumerate(self.nodes)}

    # ------------------------------------------------------------------
    def node_ratio(self, node, condition):
        """Arithmetic mean of member-gene ratios for one gene node."""
        sym = self.symbol_of.get(node, node)
        vals = []
        for g in self.genes_of.get(sym, [sym]):
            r = self.ratio[condition].get(g)
            vals.append(1.0 if (r is None or pd.isna(r)) else float(r))
        return float(np.mean(vals)) if vals else 1.0

    def initial_state(self, condition):
        """Y0 for 'Normal', 'Obese', 'NAFL' or 'NASH'."""
        y0 = np.zeros(2 * len(self.nodes))
        for n in self.nodes:
            i = 2 * self.idx[n]
            if n in self.pathways:
                y0[i] = P_INIT
            elif condition == "Normal":
                y0[i] = 1.0
            else:
                y0[i] = self.node_ratio(n, condition)
        return y0

    def inactive_index(self, node):
        return 2 * self.idx[node]

    # ------------------------------------------------------------------
    def make_rhs(self, ki=1.0, targets=SILYMARIN_TARGETS):
        nodes, idx = self.nodes, self.idx
        acts = [[idx[a] for a in sorted(self.act.get(n, ()))] for n in nodes]
        inhs = [[idx[a] for a in sorted(self.inh.get(n, ()))] for n in nodes]
        scale = np.array([ki if n in targets else 1.0 for n in nodes])
        kn = KSP ** N_HILL

        def rhs(y, t):
            y_in, y_act = y[0::2], y[1::2]
            sat = y_in ** N_HILL / (kn + y_in ** N_HILL)
            activation = np.empty(len(nodes))
            for k in range(len(nodes)):
                a = acts[k]
                rate = VMAX * sat[k] if not a else KCAT * sat[k] * y_act[a].sum()
                for j in inhs[k]:
                    rate *= kn / (kn + y_act[j] ** N_HILL)
                activation[k] = rate
            activation *= scale
            inactivation = VMAX * y_act ** N_HILL / (kn + y_act ** N_HILL)
            dydt = np.empty_like(y)
            dydt[0::2] = -activation + inactivation
            dydt[1::2] = activation - inactivation
            return dydt
        return rhs

    def simulate(self, y0, ki=1.0, t_end=300.0, n_points=3001):
        t = np.linspace(0.0, t_end, n_points)
        y = odeint(self.make_rhs(ki), y0, t, mxstep=10000)
        return t, y

    def auc(self, t, y, output):
        """Trapezoidal AUC of the active-form trajectory."""
        return float(_trapz(y[:, 2 * self.idx[output] + 1], t))


def stage_advantage(model, y0_nafl, y0_nash, ki=0.3, outputs=CORE_OUTPUTS):
    """Percentage AUC reduction at each stage and the NAFL/NASH advantage ratio."""
    red = {}
    for stage, y0 in (("NAFL", y0_nafl), ("NASH", y0_nash)):
        t, y_ctrl = model.simulate(y0, ki=1.0)
        _, y_drug = model.simulate(y0, ki=ki)
        red[stage] = {}
        for o in outputs:
            a0 = model.auc(t, y_ctrl, o)
            red[stage][o] = 100.0 * (a0 - model.auc(t, y_drug, o)) / a0
    return {o: {"NAFL": red["NAFL"][o], "NASH": red["NASH"][o],
                "ratio": red["NAFL"][o] / red["NASH"][o] if red["NASH"][o] else np.nan}
            for o in outputs}
