#!/usr/bin/env python3
"""
ODE Model v8 | iv_type=pydeseq2 | ratio_condition=NAFL_vs_Normal
========================================================================
Label           : pyDESeq2 ratio (2^log2FC) [UNIFIED]
Ratio condition : NAFL_vs_Normal
  Numerator     : NAFL
  Denominator   : Normal (Normal, implicit = 1.0)
  Gene IV       : NAFL_expr / Normal_expr  (ratio-based)
  Pathway IV    : 100.0 (fixed, per prior papers)
Node naming     : KEGG hsa04932 display names (v8)
Format          : v4
Generated       : 2026-07-08 06:23:13.450928
Interactions    : result_v4_symbol_interactions.xlsx
Nodes v3        : node_name_table_hsa04932.xlsx
Genes           : 58
Pathways        : 12
StateVars       : 140
"""


# ROBUSTNESS VARIANT  |  Hill n = 2.0  |  ksp = 4.0  |  Vmax = kcat = 2.0 (fixed)
# Generated by generate_robustness_models.py for parameter sensitivity analysis.

import numpy as np
from scipy.integrate import odeint
import matplotlib.pyplot as plt
import pandas as pd

MODEL_INFO = {
    'iv_type':         'pydeseq2',
    'iv_label':        'pyDESeq2 ratio (2^log2FC) [UNIFIED]',
    'ratio_condition': 'NAFL_vs_Normal',
    'num_condition':   'NAFL',
    'denom_condition': 'Normal',
    'version':         'v8',
    'n_genes':         58,
    'n_pathways':      12,
    'pathway_initial_inactive': 100.0,
    'gene_iv_method':  'ratio = condition_expr / Normal_expr',
}

PARAMS = {
    'Vmax': 2.0,
    'ksp' : 4.0,
    'n'   : 2.0,
    'kcat': 2.0,
}

STATE_VARS = [
    'ACDC_inactive',  # ADIPOQ
    'ACDC_active',    # ADIPOQ
    'AMPK_inactive',  # PRKAG2
    'AMPK_active',    # PRKAG2
    'AP_1_inactive',  # FOS
    'AP_1_active',    # FOS
    'ASK1_inactive',  # MAP3K5
    'ASK1_active',    # MAP3K5
    'ATF4_inactive',  # ATF4
    'ATF4_active',    # ATF4
    'Akt_inactive',  # AKT3
    'Akt_active',    # AKT3
    'Bax_inactive',  # BAX
    'Bax_active',    # BAX
    'Bid_inactive',  # BID
    'Bid_active',    # BID
    'Bim_inactive',  # BCL2L11
    'Bim_active',    # BCL2L11
    'CASP3_inactive',  # CASP3
    'CASP3_active',    # CASP3
    'CASP7_inactive',  # CASP7
    'CASP7_active',    # CASP7
    'CASP8_inactive',  # CASP8
    'CASP8_active',    # CASP8
    'CHOP_inactive',  # DDIT3
    'CHOP_active',    # DDIT3
    'CYP2E1_inactive',  # CYP2E1
    'CYP2E1_active',    # CYP2E1
    'C_EBPa_inactive',  # CEBPA
    'C_EBPa_active',    # CEBPA
    'Cdc42_inactive',  # CDC42
    'Cdc42_active',    # CDC42
    'ChREBP_inactive',  # MLXIP
    'ChREBP_active',    # MLXIP
    'CxI_inactive',  # NDUFC2-KCTD14
    'CxI_active',    # NDUFC2-KCTD14
    'CxII_inactive',  # SDHA
    'CxII_active',    # SDHA
    'CxIII_inactive',  # UQCR11
    'CxIII_active',    # UQCR11
    'CxIV_inactive',  # COX6B2
    'CxIV_active',    # COX6B2
    'Cytc_inactive',  # CYCS
    'Cytc_active',    # CYCS
    'Fas_inactive',  # FAS
    'Fas_active',    # FAS
    'FasL_inactive',  # FASLG
    'FasL_active',    # FASLG
    'GSK_3_inactive',  # GSK3A
    'GSK_3_active',    # GSK3A
    'IKKb_inactive',  # IKBKB
    'IKKb_active',    # IKBKB
    'IL_1_inactive',  # IL1A
    'IL_1_active',    # IL1A
    'IL_6_inactive',  # IL6
    'IL_6_active',    # IL6
    'IL_6R_inactive',  # IL6R
    'IL_6R_active',    # IL6R
    'IL_8_inactive',  # CXCL8
    'IL_8_active',    # CXCL8
    'INS_inactive',  # INS
    'INS_active',    # INS
    'INSR_inactive',  # INSR
    'INSR_active',    # INSR
    'IRE1a_inactive',  # ERN1
    'IRE1a_active',    # ERN1
    'IRS_1_2_inactive',  # IRS1
    'IRS_1_2_active',    # IRS1
    'ITCH_inactive',  # ITCH
    'ITCH_active',    # ITCH
    'JNK1_2_inactive',  # MAPK8
    'JNK1_2_active',    # MAPK8
    'LEP_inactive',  # LEP
    'LEP_active',    # LEP
    'LXR_a_inactive',  # NR1H3
    'LXR_a_active',    # NR1H3
    'L_PK_inactive',  # PKLR
    'L_PK_active',    # PKLR
    'MLK3_inactive',  # MAP3K11
    'MLK3_active',    # MAP3K11
    'NF_kB_inactive',  # NFKB1
    'NF_kB_active',    # NFKB1
    'ObR_inactive',  # LEPR
    'ObR_active',    # LEPR
    'PERK_inactive',  # EIF2AK3
    'PERK_active',    # EIF2AK3
    'PI3K_inactive',  # P3R3URF-PIK3R3
    'PI3K_active',    # P3R3URF-PIK3R3
    'PPAR_a_inactive',  # PPARA
    'PPAR_a_active',    # PPARA
    'PPAR_g_inactive',  # PPARG
    'PPAR_g_active',    # PPARG
    'RXR_inactive',  # RXRA
    'RXR_active',    # RXRA
    'Rac1_inactive',  # RAC1
    'Rac1_active',    # RAC1
    'SOCS3_inactive',  # SOCS3
    'SOCS3_active',    # SOCS3
    'SREBP_1c_inactive',  # SREBF1
    'SREBP_1c_active',    # SREBF1
    'TGF_b1_inactive',  # TGFB1
    'TGF_b1_active',    # TGFB1
    'TNFR1_inactive',  # TNFRSF1A
    'TNFR1_active',    # TNFRSF1A
    'TNFa_inactive',  # TNF
    'TNFa_active',    # TNF
    'TRAF2_inactive',  # TRAF2
    'TRAF2_active',    # TRAF2
    'XBP1_inactive',  # XBP1
    'XBP1_active',    # XBP1
    'adipoR_inactive',  # ADIPOR1
    'adipoR_active',    # ADIPOR1
    'eIF2a_inactive',  # EIF2S1
    'eIF2a_active',    # EIF2S1
    'p38_inactive',  # MAPK14
    'p38_active',    # MAPK14
    'P_Adipogenesis_inactive',  # Pathway: P_Adipogenesis
    'P_Adipogenesis_active',    # Pathway: P_Adipogenesis
    'P_Apoptosis_inactive',  # Pathway: P_Apoptosis
    'P_Apoptosis_active',    # Pathway: P_Apoptosis
    'P_Cell_death_inactive',  # Pathway: P_Cell_death
    'P_Cell_death_active',    # Pathway: P_Cell_death
    'P_De_novo_fatty_acid_synthesis_inactive',  # Pathway: P_De_novo_fatty_acid_synthesis
    'P_De_novo_fatty_acid_synthesis_active',    # Pathway: P_De_novo_fatty_acid_synthesis
    'P_Development_of_NAFLD_inactive',  # Pathway: P_Development_of_NAFLD
    'P_Development_of_NAFLD_active',    # Pathway: P_Development_of_NAFLD
    'P_Development_of_steatohepatitis_inactive',  # Pathway: P_Development_of_steatohepatitis
    'P_Development_of_steatohepatitis_active',    # Pathway: P_Development_of_steatohepatitis
    'P_Fibrosis_inactive',  # Pathway: P_Fibrosis
    'P_Fibrosis_active',    # Pathway: P_Fibrosis
    'P_HCC_proliferation_inactive',  # Pathway: P_HCC_proliferation
    'P_HCC_proliferation_active',    # Pathway: P_HCC_proliferation
    'P_Hepatocyte_injury_inactive',  # Pathway: P_Hepatocyte_injury
    'P_Hepatocyte_injury_active',    # Pathway: P_Hepatocyte_injury
    'P_Hyperinsulinemia_inactive',  # Pathway: P_Hyperinsulinemia
    'P_Hyperinsulinemia_active',    # Pathway: P_Hyperinsulinemia
    'P_Improvement_of_NAFLD_inactive',  # Pathway: P_Improvement_of_NAFLD
    'P_Improvement_of_NAFLD_active',    # Pathway: P_Improvement_of_NAFLD
    'P_Inflammation_inactive',  # Pathway: P_Inflammation
    'P_Inflammation_active',    # Pathway: P_Inflammation
]

GENE_METADATA = {
    'ACDC': {'symbol': 'ADIPOQ', 'kegg_display_name': 'ACDC', 'initial_ratio': 1.65605391820818},  # KEGG: ACDC | ratio=1.6561
    'AMPK': {'symbol': 'PRKAG2', 'kegg_display_name': 'AMPK', 'initial_ratio': 1.3802739646132045},  # KEGG: AMPK | ratio=1.3803
    'AP_1': {'symbol': 'FOS', 'kegg_display_name': 'AP_1', 'initial_ratio': 1.043390649886129},  # KEGG: AP_1 | ratio=1.0434
    'ASK1': {'symbol': 'MAP3K5', 'kegg_display_name': 'ASK1', 'initial_ratio': 0.9570138812941216},  # KEGG: ASK1 | ratio=0.9570
    'ATF4': {'symbol': 'ATF4', 'kegg_display_name': 'ATF4', 'initial_ratio': 1.477317180569543},  # KEGG: ATF4 | ratio=1.4773
    'Akt': {'symbol': 'AKT3', 'kegg_display_name': 'Akt', 'initial_ratio': 0.844789213234778},  # KEGG: Akt | ratio=0.8448
    'Bax': {'symbol': 'BAX', 'kegg_display_name': 'Bax', 'initial_ratio': 1.661160392435531},  # KEGG: Bax | ratio=1.6612
    'Bid': {'symbol': 'BID', 'kegg_display_name': 'Bid', 'initial_ratio': 1.196597055828184},  # KEGG: Bid | ratio=1.1966
    'Bim': {'symbol': 'BCL2L11', 'kegg_display_name': 'Bim', 'initial_ratio': 1.008548559673017},  # KEGG: Bim | ratio=1.0085
    'CASP3': {'symbol': 'CASP3', 'kegg_display_name': 'CASP3', 'initial_ratio': 1.325909516561105},  # KEGG: CASP3 | ratio=1.3259
    'CASP7': {'symbol': 'CASP7', 'kegg_display_name': 'CASP7', 'initial_ratio': 2.09295906894705},  # KEGG: CASP7 | ratio=2.0930
    'CASP8': {'symbol': 'CASP8', 'kegg_display_name': 'CASP8', 'initial_ratio': 1.393729091456869},  # KEGG: CASP8 | ratio=1.3937
    'CHOP': {'symbol': 'DDIT3', 'kegg_display_name': 'CHOP', 'initial_ratio': 2.002614249283768},  # KEGG: CHOP | ratio=2.0026
    'CYP2E1': {'symbol': 'CYP2E1', 'kegg_display_name': 'CYP2E1', 'initial_ratio': 0.6848004135629803},  # KEGG: CYP2E1 | ratio=0.6848
    'C_EBPa': {'symbol': 'CEBPA', 'kegg_display_name': 'C_EBPa', 'initial_ratio': 1.536754804029567},  # KEGG: C_EBPa | ratio=1.5368
    'Cdc42': {'symbol': 'CDC42', 'kegg_display_name': 'Cdc42', 'initial_ratio': 1.069167484947884},  # KEGG: Cdc42 | ratio=1.0692
    'ChREBP': {'symbol': 'MLXIP', 'kegg_display_name': 'ChREBP', 'initial_ratio': 0.9722606728792957},  # KEGG: ChREBP | ratio=0.9723
    'CxI': {'symbol': 'NDUFC2-KCTD14', 'kegg_display_name': 'CxI', 'initial_ratio': 1.2233088624411732},  # KEGG: CxI | ratio=1.2233
    'CxII': {'symbol': 'SDHA', 'kegg_display_name': 'CxII', 'initial_ratio': 1.1702553967520686},  # KEGG: CxII | ratio=1.1703
    'CxIII': {'symbol': 'UQCR11', 'kegg_display_name': 'CxIII', 'initial_ratio': 1.3241866718203383},  # KEGG: CxIII | ratio=1.3242
    'CxIV': {'symbol': 'COX6B2', 'kegg_display_name': 'CxIV', 'initial_ratio': 1.4802769724446327},  # KEGG: CxIV | ratio=1.4803
    'Cytc': {'symbol': 'CYCS', 'kegg_display_name': 'Cytc', 'initial_ratio': 2.494774333860483},  # KEGG: Cytc | ratio=2.4948
    'Fas': {'symbol': 'FAS', 'kegg_display_name': 'Fas', 'initial_ratio': 1.260772771192321},  # KEGG: Fas | ratio=1.2608
    'FasL': {'symbol': 'FASLG', 'kegg_display_name': 'FasL', 'initial_ratio': 0.7786168945244901},  # KEGG: FasL | ratio=0.7786
    'GSK_3': {'symbol': 'GSK3A', 'kegg_display_name': 'GSK_3', 'initial_ratio': 0.9933907292751505},  # KEGG: GSK_3 | ratio=0.9934
    'IKKb': {'symbol': 'IKBKB', 'kegg_display_name': 'IKKb', 'initial_ratio': 0.7973856342649832},  # KEGG: IKKb | ratio=0.7974
    'IL_1': {'symbol': 'IL1A', 'kegg_display_name': 'IL_1', 'initial_ratio': 1.3418949936808156},  # KEGG: IL_1 | ratio=1.3419
    'IL_6': {'symbol': 'IL6', 'kegg_display_name': 'IL_6', 'initial_ratio': 2.123626481511045},  # KEGG: IL_6 | ratio=2.1236
    'IL_6R': {'symbol': 'IL6R', 'kegg_display_name': 'IL_6R', 'initial_ratio': 0.7630394859374182},  # KEGG: IL_6R | ratio=0.7630
    'IL_8': {'symbol': 'CXCL8', 'kegg_display_name': 'IL_8', 'initial_ratio': 2.915138893874332},  # KEGG: IL_8 | ratio=2.9151
    'INS': {'symbol': 'INS', 'kegg_display_name': 'INS', 'initial_ratio': 1.0},  # KEGG: INS | ratio=1.0000
    'INSR': {'symbol': 'INSR', 'kegg_display_name': 'INSR', 'initial_ratio': 0.7957786706565789},  # KEGG: INSR | ratio=0.7958
    'IRE1a': {'symbol': 'ERN1', 'kegg_display_name': 'IRE1a', 'initial_ratio': 0.4595591632821761},  # KEGG: IRE1a | ratio=0.4596
    'IRS_1_2': {'symbol': 'IRS1', 'kegg_display_name': 'IRS_1_2', 'initial_ratio': 0.7824623232337802},  # KEGG: IRS_1_2 | ratio=0.7825
    'ITCH': {'symbol': 'ITCH', 'kegg_display_name': 'ITCH', 'initial_ratio': 0.6624305293379386},  # KEGG: ITCH | ratio=0.6624
    'JNK1_2': {'symbol': 'MAPK8', 'kegg_display_name': 'JNK1_2', 'initial_ratio': 1.0186217407796878},  # KEGG: JNK1_2 | ratio=1.0186
    'LEP': {'symbol': 'LEP', 'kegg_display_name': 'LEP', 'initial_ratio': 0.8795708409003137},  # KEGG: LEP | ratio=0.8796
    'LXR_a': {'symbol': 'NR1H3', 'kegg_display_name': 'LXR_a', 'initial_ratio': 1.004076628265495},  # KEGG: LXR_a | ratio=1.0041
    'L_PK': {'symbol': 'PKLR', 'kegg_display_name': 'L_PK', 'initial_ratio': 0.9260188790791141},  # KEGG: L_PK | ratio=0.9260
    'MLK3': {'symbol': 'MAP3K11', 'kegg_display_name': 'MLK3', 'initial_ratio': 0.9682536975674751},  # KEGG: MLK3 | ratio=0.9683
    'NF_kB': {'symbol': 'NFKB1', 'kegg_display_name': 'NF_kB', 'initial_ratio': 0.7411794701844725},  # KEGG: NF_kB | ratio=0.7412
    'ObR': {'symbol': 'LEPR', 'kegg_display_name': 'ObR', 'initial_ratio': 0.392766840442728},  # KEGG: ObR | ratio=0.3928
    'PERK': {'symbol': 'EIF2AK3', 'kegg_display_name': 'PERK', 'initial_ratio': 1.201684107495176},  # KEGG: PERK | ratio=1.2017
    'PI3K': {'symbol': 'P3R3URF-PIK3R3', 'kegg_display_name': 'PI3K', 'initial_ratio': 0.9863484267860975},  # KEGG: PI3K | ratio=0.9863
    'PPAR_a': {'symbol': 'PPARA', 'kegg_display_name': 'PPAR_a', 'initial_ratio': 0.6789402445370519},  # KEGG: PPAR_a | ratio=0.6789
    'PPAR_g': {'symbol': 'PPARG', 'kegg_display_name': 'PPAR_g', 'initial_ratio': 1.137417287651299},  # KEGG: PPAR_g | ratio=1.1374
    'RXR': {'symbol': 'RXRA', 'kegg_display_name': 'RXR', 'initial_ratio': 0.7755543679424535},  # KEGG: RXR | ratio=0.7756
    'Rac1': {'symbol': 'RAC1', 'kegg_display_name': 'Rac1', 'initial_ratio': 1.135423927263715},  # KEGG: Rac1 | ratio=1.1354
    'SOCS3': {'symbol': 'SOCS3', 'kegg_display_name': 'SOCS3', 'initial_ratio': 0.850319188491571},  # KEGG: SOCS3 | ratio=0.8503
    'SREBP_1c': {'symbol': 'SREBF1', 'kegg_display_name': 'SREBP_1c', 'initial_ratio': 0.9640069380425924},  # KEGG: SREBP_1c | ratio=0.9640
    'TGF_b1': {'symbol': 'TGFB1', 'kegg_display_name': 'TGF_b1', 'initial_ratio': 0.419874720699413},  # KEGG: TGF_b1 | ratio=0.4199
    'TNFR1': {'symbol': 'TNFRSF1A', 'kegg_display_name': 'TNFR1', 'initial_ratio': 0.6871184713679886},  # KEGG: TNFR1 | ratio=0.6871
    'TNFa': {'symbol': 'TNF', 'kegg_display_name': 'TNFa', 'initial_ratio': 1.599326416392565},  # KEGG: TNFa | ratio=1.5993
    'TRAF2': {'symbol': 'TRAF2', 'kegg_display_name': 'TRAF2', 'initial_ratio': 1.144991338473556},  # KEGG: TRAF2 | ratio=1.1450
    'XBP1': {'symbol': 'XBP1', 'kegg_display_name': 'XBP1', 'initial_ratio': 1.436371624214072},  # KEGG: XBP1 | ratio=1.4364
    'adipoR': {'symbol': 'ADIPOR1', 'kegg_display_name': 'adipoR', 'initial_ratio': 1.3388951394524127},  # KEGG: adipoR | ratio=1.3389
    'eIF2a': {'symbol': 'EIF2S1', 'kegg_display_name': 'eIF2a', 'initial_ratio': 1.115558255487487},  # KEGG: eIF2a | ratio=1.1156
    'p38': {'symbol': 'MAPK14', 'kegg_display_name': 'p38', 'initial_ratio': 1.0891494002857076},  # KEGG: p38 | ratio=1.0891
}

PATHWAY_METADATA = {
    'P_Adipogenesis': {'pathway_name': 'P_Adipogenesis', 'type': 'pathway_output', 'initial_level': 100.0},  # initial_inactive=100.0
    'P_Apoptosis': {'pathway_name': 'P_Apoptosis', 'type': 'pathway_output', 'initial_level': 100.0},  # initial_inactive=100.0
    'P_Cell_death': {'pathway_name': 'P_Cell_death', 'type': 'pathway_output', 'initial_level': 100.0},  # initial_inactive=100.0
    'P_De_novo_fatty_acid_synthesis': {'pathway_name': 'P_De_novo_fatty_acid_synthesis', 'type': 'pathway_output', 'initial_level': 100.0},  # initial_inactive=100.0
    'P_Development_of_NAFLD': {'pathway_name': 'P_Development_of_NAFLD', 'type': 'pathway_output', 'initial_level': 100.0},  # initial_inactive=100.0
    'P_Development_of_steatohepatitis': {'pathway_name': 'P_Development_of_steatohepatitis', 'type': 'pathway_output', 'initial_level': 100.0},  # initial_inactive=100.0
    'P_Fibrosis': {'pathway_name': 'P_Fibrosis', 'type': 'pathway_output', 'initial_level': 100.0},  # initial_inactive=100.0
    'P_HCC_proliferation': {'pathway_name': 'P_HCC_proliferation', 'type': 'pathway_output', 'initial_level': 100.0},  # initial_inactive=100.0
    'P_Hepatocyte_injury': {'pathway_name': 'P_Hepatocyte_injury', 'type': 'pathway_output', 'initial_level': 100.0},  # initial_inactive=100.0
    'P_Hyperinsulinemia': {'pathway_name': 'P_Hyperinsulinemia', 'type': 'pathway_output', 'initial_level': 100.0},  # initial_inactive=100.0
    'P_Improvement_of_NAFLD': {'pathway_name': 'P_Improvement_of_NAFLD', 'type': 'pathway_output', 'initial_level': 100.0},  # initial_inactive=100.0
    'P_Inflammation': {'pathway_name': 'P_Inflammation', 'type': 'pathway_output', 'initial_level': 100.0},  # initial_inactive=100.0
}

# =============================================================================
# Initial conditions (v7 design):
#   Gene nodes   : inactive = ratio (condition/Normal), active = 0
#   Pathway nodes: inactive = 100.0 (fixed), active = 0
# =============================================================================
Y0 = np.zeros(len(STATE_VARS))
for _i, _var in enumerate(STATE_VARS):
    if '_inactive' in _var:
        _node = _var.replace('_inactive', '')
        if _node in PATHWAY_METADATA:
            Y0[_i] = PATHWAY_METADATA[_node].get('initial_level',
                                                  100.0)
        elif _node in GENE_METADATA:
            Y0[_i] = GENE_METADATA[_node].get('initial_ratio', 1.0)
        else:
            Y0[_i] = 1.0


def ode_system(y, t, params=None):
    """ODE system equations."""
    if params is None:
        params = PARAMS
    Vmax = params['Vmax']
    ksp  = params['ksp']
    n    = params['n']
    kcat = params['kcat']

    # ADIPOQ
    ACDC_inactive = y[0]
    ACDC_active   = y[1]

    # PRKAG2
    AMPK_inactive = y[2]
    AMPK_active   = y[3]

    # FOS
    AP_1_inactive = y[4]
    AP_1_active   = y[5]

    # MAP3K5
    ASK1_inactive = y[6]
    ASK1_active   = y[7]

    # ATF4
    ATF4_inactive = y[8]
    ATF4_active   = y[9]

    # AKT3
    Akt_inactive = y[10]
    Akt_active   = y[11]

    # BAX
    Bax_inactive = y[12]
    Bax_active   = y[13]

    # BID
    Bid_inactive = y[14]
    Bid_active   = y[15]

    # BCL2L11
    Bim_inactive = y[16]
    Bim_active   = y[17]

    # CASP3
    CASP3_inactive = y[18]
    CASP3_active   = y[19]

    # CASP7
    CASP7_inactive = y[20]
    CASP7_active   = y[21]

    # CASP8
    CASP8_inactive = y[22]
    CASP8_active   = y[23]

    # DDIT3
    CHOP_inactive = y[24]
    CHOP_active   = y[25]

    # CYP2E1
    CYP2E1_inactive = y[26]
    CYP2E1_active   = y[27]

    # CEBPA
    C_EBPa_inactive = y[28]
    C_EBPa_active   = y[29]

    # CDC42
    Cdc42_inactive = y[30]
    Cdc42_active   = y[31]

    # MLXIP
    ChREBP_inactive = y[32]
    ChREBP_active   = y[33]

    # NDUFC2-KCTD14
    CxI_inactive = y[34]
    CxI_active   = y[35]

    # SDHA
    CxII_inactive = y[36]
    CxII_active   = y[37]

    # UQCR11
    CxIII_inactive = y[38]
    CxIII_active   = y[39]

    # COX6B2
    CxIV_inactive = y[40]
    CxIV_active   = y[41]

    # CYCS
    Cytc_inactive = y[42]
    Cytc_active   = y[43]

    # FAS
    Fas_inactive = y[44]
    Fas_active   = y[45]

    # FASLG
    FasL_inactive = y[46]
    FasL_active   = y[47]

    # GSK3A
    GSK_3_inactive = y[48]
    GSK_3_active   = y[49]

    # IKBKB
    IKKb_inactive = y[50]
    IKKb_active   = y[51]

    # IL1A
    IL_1_inactive = y[52]
    IL_1_active   = y[53]

    # IL6
    IL_6_inactive = y[54]
    IL_6_active   = y[55]

    # IL6R
    IL_6R_inactive = y[56]
    IL_6R_active   = y[57]

    # CXCL8
    IL_8_inactive = y[58]
    IL_8_active   = y[59]

    # INS
    INS_inactive = y[60]
    INS_active   = y[61]

    # INSR
    INSR_inactive = y[62]
    INSR_active   = y[63]

    # ERN1
    IRE1a_inactive = y[64]
    IRE1a_active   = y[65]

    # IRS1
    IRS_1_2_inactive = y[66]
    IRS_1_2_active   = y[67]

    # ITCH
    ITCH_inactive = y[68]
    ITCH_active   = y[69]

    # MAPK8
    JNK1_2_inactive = y[70]
    JNK1_2_active   = y[71]

    # LEP
    LEP_inactive = y[72]
    LEP_active   = y[73]

    # NR1H3
    LXR_a_inactive = y[74]
    LXR_a_active   = y[75]

    # PKLR
    L_PK_inactive = y[76]
    L_PK_active   = y[77]

    # MAP3K11
    MLK3_inactive = y[78]
    MLK3_active   = y[79]

    # NFKB1
    NF_kB_inactive = y[80]
    NF_kB_active   = y[81]

    # LEPR
    ObR_inactive = y[82]
    ObR_active   = y[83]

    # EIF2AK3
    PERK_inactive = y[84]
    PERK_active   = y[85]

    # P3R3URF-PIK3R3
    PI3K_inactive = y[86]
    PI3K_active   = y[87]

    # PPARA
    PPAR_a_inactive = y[88]
    PPAR_a_active   = y[89]

    # PPARG
    PPAR_g_inactive = y[90]
    PPAR_g_active   = y[91]

    # RXRA
    RXR_inactive = y[92]
    RXR_active   = y[93]

    # RAC1
    Rac1_inactive = y[94]
    Rac1_active   = y[95]

    # SOCS3
    SOCS3_inactive = y[96]
    SOCS3_active   = y[97]

    # SREBF1
    SREBP_1c_inactive = y[98]
    SREBP_1c_active   = y[99]

    # TGFB1
    TGF_b1_inactive = y[100]
    TGF_b1_active   = y[101]

    # TNFRSF1A
    TNFR1_inactive = y[102]
    TNFR1_active   = y[103]

    # TNF
    TNFa_inactive = y[104]
    TNFa_active   = y[105]

    # TRAF2
    TRAF2_inactive = y[106]
    TRAF2_active   = y[107]

    # XBP1
    XBP1_inactive = y[108]
    XBP1_active   = y[109]

    # ADIPOR1
    adipoR_inactive = y[110]
    adipoR_active   = y[111]

    # EIF2S1
    eIF2a_inactive = y[112]
    eIF2a_active   = y[113]

    # MAPK14
    p38_inactive = y[114]
    p38_active   = y[115]

    # Pathway: P_Adipogenesis
    P_Adipogenesis_inactive = y[116]
    P_Adipogenesis_active   = y[117]

    # Pathway: P_Apoptosis
    P_Apoptosis_inactive = y[118]
    P_Apoptosis_active   = y[119]

    # Pathway: P_Cell_death
    P_Cell_death_inactive = y[120]
    P_Cell_death_active   = y[121]

    # Pathway: P_De_novo_fatty_acid_synthesis
    P_De_novo_fatty_acid_synthesis_inactive = y[122]
    P_De_novo_fatty_acid_synthesis_active   = y[123]

    # Pathway: P_Development_of_NAFLD
    P_Development_of_NAFLD_inactive = y[124]
    P_Development_of_NAFLD_active   = y[125]

    # Pathway: P_Development_of_steatohepatitis
    P_Development_of_steatohepatitis_inactive = y[126]
    P_Development_of_steatohepatitis_active   = y[127]

    # Pathway: P_Fibrosis
    P_Fibrosis_inactive = y[128]
    P_Fibrosis_active   = y[129]

    # Pathway: P_HCC_proliferation
    P_HCC_proliferation_inactive = y[130]
    P_HCC_proliferation_active   = y[131]

    # Pathway: P_Hepatocyte_injury
    P_Hepatocyte_injury_inactive = y[132]
    P_Hepatocyte_injury_active   = y[133]

    # Pathway: P_Hyperinsulinemia
    P_Hyperinsulinemia_inactive = y[134]
    P_Hyperinsulinemia_active   = y[135]

    # Pathway: P_Improvement_of_NAFLD
    P_Improvement_of_NAFLD_inactive = y[136]
    P_Improvement_of_NAFLD_active   = y[137]

    # Pathway: P_Inflammation
    P_Inflammation_inactive = y[138]
    P_Inflammation_active   = y[139]

    dydt = np.zeros_like(y)

    # ADIPOQ
    dydt[0]   = -(((2.0 * ACDC_inactive**2.0) / (4.0**2.0 + ACDC_inactive**2.0))) + ((2.0 * ACDC_active**2.0) / (4.0**2.0 + ACDC_active**2.0))
    dydt[1] = (((2.0 * ACDC_inactive**2.0) / (4.0**2.0 + ACDC_inactive**2.0))) - ((2.0 * ACDC_active**2.0) / (4.0**2.0 + ACDC_active**2.0))

    # PRKAG2
    dydt[2]   = -(((2.0 * ObR_active * AMPK_inactive**2.0) / (4.0**2.0 + AMPK_inactive**2.0)) + ((2.0 * adipoR_active * AMPK_inactive**2.0) / (4.0**2.0 + AMPK_inactive**2.0))) + ((2.0 * AMPK_active**2.0) / (4.0**2.0 + AMPK_active**2.0))
    dydt[3] = (((2.0 * ObR_active * AMPK_inactive**2.0) / (4.0**2.0 + AMPK_inactive**2.0)) + ((2.0 * adipoR_active * AMPK_inactive**2.0) / (4.0**2.0 + AMPK_inactive**2.0))) - ((2.0 * AMPK_active**2.0) / (4.0**2.0 + AMPK_active**2.0))

    # FOS
    dydt[4]   = -(((2.0 * JNK1_2_active * AP_1_inactive**2.0) / (4.0**2.0 + AP_1_inactive**2.0))) + ((2.0 * AP_1_active**2.0) / (4.0**2.0 + AP_1_active**2.0))
    dydt[5] = (((2.0 * JNK1_2_active * AP_1_inactive**2.0) / (4.0**2.0 + AP_1_inactive**2.0))) - ((2.0 * AP_1_active**2.0) / (4.0**2.0 + AP_1_active**2.0))

    # MAP3K5
    dydt[6]   = -(((2.0 * TRAF2_active * ASK1_inactive**2.0) / (4.0**2.0 + ASK1_inactive**2.0))) + ((2.0 * ASK1_active**2.0) / (4.0**2.0 + ASK1_active**2.0))
    dydt[7] = (((2.0 * TRAF2_active * ASK1_inactive**2.0) / (4.0**2.0 + ASK1_inactive**2.0))) - ((2.0 * ASK1_active**2.0) / (4.0**2.0 + ASK1_active**2.0))

    # ATF4
    dydt[8]   = -(((2.0 * eIF2a_active * ATF4_inactive**2.0) / (4.0**2.0 + ATF4_inactive**2.0))) + ((2.0 * ATF4_active**2.0) / (4.0**2.0 + ATF4_active**2.0))
    dydt[9] = (((2.0 * eIF2a_active * ATF4_inactive**2.0) / (4.0**2.0 + ATF4_inactive**2.0))) - ((2.0 * ATF4_active**2.0) / (4.0**2.0 + ATF4_active**2.0))

    # AKT3
    dydt[10]   = -(((2.0 * PI3K_active * Akt_inactive**2.0) / (4.0**2.0 + Akt_inactive**2.0))) + ((2.0 * Akt_active**2.0) / (4.0**2.0 + Akt_active**2.0))
    dydt[11] = (((2.0 * PI3K_active * Akt_inactive**2.0) / (4.0**2.0 + Akt_inactive**2.0))) - ((2.0 * Akt_active**2.0) / (4.0**2.0 + Akt_active**2.0))

    # BAX
    dydt[12]   = -(((2.0 * Bim_active * Bax_inactive**2.0) / (4.0**2.0 + Bax_inactive**2.0)) + ((2.0 * Bid_active * Bax_inactive**2.0) / (4.0**2.0 + Bax_inactive**2.0))) + ((2.0 * Bax_active**2.0) / (4.0**2.0 + Bax_active**2.0))
    dydt[13] = (((2.0 * Bim_active * Bax_inactive**2.0) / (4.0**2.0 + Bax_inactive**2.0)) + ((2.0 * Bid_active * Bax_inactive**2.0) / (4.0**2.0 + Bax_inactive**2.0))) - ((2.0 * Bax_active**2.0) / (4.0**2.0 + Bax_active**2.0))

    # BID
    dydt[14]   = -(((2.0 * CASP8_active * Bid_inactive**2.0) / (4.0**2.0 + Bid_inactive**2.0))) + ((2.0 * Bid_active**2.0) / (4.0**2.0 + Bid_active**2.0))
    dydt[15] = (((2.0 * CASP8_active * Bid_inactive**2.0) / (4.0**2.0 + Bid_inactive**2.0))) - ((2.0 * Bid_active**2.0) / (4.0**2.0 + Bid_active**2.0))

    # BCL2L11
    dydt[16]   = -(((2.0 * CHOP_active * Bim_inactive**2.0) / (4.0**2.0 + Bim_inactive**2.0))) + ((2.0 * Bim_active**2.0) / (4.0**2.0 + Bim_active**2.0))
    dydt[17] = (((2.0 * CHOP_active * Bim_inactive**2.0) / (4.0**2.0 + Bim_inactive**2.0))) - ((2.0 * Bim_active**2.0) / (4.0**2.0 + Bim_active**2.0))

    # CASP3
    dydt[18]   = -(((2.0 * Cytc_active * CASP3_inactive**2.0) / (4.0**2.0 + CASP3_inactive**2.0))) + ((2.0 * CASP3_active**2.0) / (4.0**2.0 + CASP3_active**2.0))
    dydt[19] = (((2.0 * Cytc_active * CASP3_inactive**2.0) / (4.0**2.0 + CASP3_inactive**2.0))) - ((2.0 * CASP3_active**2.0) / (4.0**2.0 + CASP3_active**2.0))

    # CASP7
    dydt[20]   = -(((2.0 * Cytc_active * CASP7_inactive**2.0) / (4.0**2.0 + CASP7_inactive**2.0))) + ((2.0 * CASP7_active**2.0) / (4.0**2.0 + CASP7_active**2.0))
    dydt[21] = (((2.0 * Cytc_active * CASP7_inactive**2.0) / (4.0**2.0 + CASP7_inactive**2.0))) - ((2.0 * CASP7_active**2.0) / (4.0**2.0 + CASP7_active**2.0))

    # CASP8
    dydt[22]   = -(((2.0 * ITCH_active * CASP8_inactive**2.0) / (4.0**2.0 + CASP8_inactive**2.0)) + ((2.0 * Fas_active * CASP8_inactive**2.0) / (4.0**2.0 + CASP8_inactive**2.0))) + ((2.0 * CASP8_active**2.0) / (4.0**2.0 + CASP8_active**2.0))
    dydt[23] = (((2.0 * ITCH_active * CASP8_inactive**2.0) / (4.0**2.0 + CASP8_inactive**2.0)) + ((2.0 * Fas_active * CASP8_inactive**2.0) / (4.0**2.0 + CASP8_inactive**2.0))) - ((2.0 * CASP8_active**2.0) / (4.0**2.0 + CASP8_active**2.0))

    # DDIT3
    dydt[24]   = -(((2.0 * ATF4_active * CHOP_inactive**2.0) / (4.0**2.0 + CHOP_inactive**2.0))) + ((2.0 * CHOP_active**2.0) / (4.0**2.0 + CHOP_active**2.0))
    dydt[25] = (((2.0 * ATF4_active * CHOP_inactive**2.0) / (4.0**2.0 + CHOP_inactive**2.0))) - ((2.0 * CHOP_active**2.0) / (4.0**2.0 + CHOP_active**2.0))

    # CYP2E1
    dydt[26]   = -(((2.0 * CYP2E1_inactive**2.0) / (4.0**2.0 + CYP2E1_inactive**2.0))) + ((2.0 * CYP2E1_active**2.0) / (4.0**2.0 + CYP2E1_active**2.0))
    dydt[27] = (((2.0 * CYP2E1_inactive**2.0) / (4.0**2.0 + CYP2E1_inactive**2.0))) - ((2.0 * CYP2E1_active**2.0) / (4.0**2.0 + CYP2E1_active**2.0))

    # CEBPA
    dydt[28]   = -(((2.0 * XBP1_active * C_EBPa_inactive**2.0) / (4.0**2.0 + C_EBPa_inactive**2.0))) + ((2.0 * C_EBPa_active**2.0) / (4.0**2.0 + C_EBPa_active**2.0))
    dydt[29] = (((2.0 * XBP1_active * C_EBPa_inactive**2.0) / (4.0**2.0 + C_EBPa_inactive**2.0))) - ((2.0 * C_EBPa_active**2.0) / (4.0**2.0 + C_EBPa_active**2.0))

    # CDC42
    dydt[30]   = -(((2.0 * Cdc42_inactive**2.0) / (4.0**2.0 + Cdc42_inactive**2.0))) + ((2.0 * Cdc42_active**2.0) / (4.0**2.0 + Cdc42_active**2.0))
    dydt[31] = (((2.0 * Cdc42_inactive**2.0) / (4.0**2.0 + Cdc42_inactive**2.0))) - ((2.0 * Cdc42_active**2.0) / (4.0**2.0 + Cdc42_active**2.0))

    # MLXIP
    dydt[32]   = -(((2.0 * ChREBP_inactive**2.0) / (4.0**2.0 + ChREBP_inactive**2.0))) + ((2.0 * ChREBP_active**2.0) / (4.0**2.0 + ChREBP_active**2.0))
    dydt[33] = (((2.0 * ChREBP_inactive**2.0) / (4.0**2.0 + ChREBP_inactive**2.0))) - ((2.0 * ChREBP_active**2.0) / (4.0**2.0 + ChREBP_active**2.0))

    # NDUFC2-KCTD14
    dydt[34]   = -(((2.0 * CxI_inactive**2.0) / (4.0**2.0 + CxI_inactive**2.0))) + ((2.0 * CxI_active**2.0) / (4.0**2.0 + CxI_active**2.0))
    dydt[35] = (((2.0 * CxI_inactive**2.0) / (4.0**2.0 + CxI_inactive**2.0))) - ((2.0 * CxI_active**2.0) / (4.0**2.0 + CxI_active**2.0))

    # SDHA
    dydt[36]   = -(((2.0 * CxII_inactive**2.0) / (4.0**2.0 + CxII_inactive**2.0))) + ((2.0 * CxII_active**2.0) / (4.0**2.0 + CxII_active**2.0))
    dydt[37] = (((2.0 * CxII_inactive**2.0) / (4.0**2.0 + CxII_inactive**2.0))) - ((2.0 * CxII_active**2.0) / (4.0**2.0 + CxII_active**2.0))

    # UQCR11
    dydt[38]   = -(((2.0 * CxIII_inactive**2.0) / (4.0**2.0 + CxIII_inactive**2.0))) + ((2.0 * CxIII_active**2.0) / (4.0**2.0 + CxIII_active**2.0))
    dydt[39] = (((2.0 * CxIII_inactive**2.0) / (4.0**2.0 + CxIII_inactive**2.0))) - ((2.0 * CxIII_active**2.0) / (4.0**2.0 + CxIII_active**2.0))

    # COX6B2
    dydt[40]   = -(((2.0 * CxIV_inactive**2.0) / (4.0**2.0 + CxIV_inactive**2.0))) + ((2.0 * CxIV_active**2.0) / (4.0**2.0 + CxIV_active**2.0))
    dydt[41] = (((2.0 * CxIV_inactive**2.0) / (4.0**2.0 + CxIV_inactive**2.0))) - ((2.0 * CxIV_active**2.0) / (4.0**2.0 + CxIV_active**2.0))

    # CYCS
    dydt[42]   = -(((2.0 * Bax_active * Cytc_inactive**2.0) / (4.0**2.0 + Cytc_inactive**2.0))) + ((2.0 * Cytc_active**2.0) / (4.0**2.0 + Cytc_active**2.0))
    dydt[43] = (((2.0 * Bax_active * Cytc_inactive**2.0) / (4.0**2.0 + Cytc_inactive**2.0))) - ((2.0 * Cytc_active**2.0) / (4.0**2.0 + Cytc_active**2.0))

    # FAS
    dydt[44]   = -(((2.0 * FasL_active * Fas_inactive**2.0) / (4.0**2.0 + Fas_inactive**2.0))) + ((2.0 * Fas_active**2.0) / (4.0**2.0 + Fas_active**2.0))
    dydt[45] = (((2.0 * FasL_active * Fas_inactive**2.0) / (4.0**2.0 + Fas_inactive**2.0))) - ((2.0 * Fas_active**2.0) / (4.0**2.0 + Fas_active**2.0))

    # FASLG
    dydt[46]   = -(((2.0 * CxIV_active * FasL_inactive**2.0) / (4.0**2.0 + FasL_inactive**2.0)) + ((2.0 * CYP2E1_active * FasL_inactive**2.0) / (4.0**2.0 + FasL_inactive**2.0)) + ((2.0 * CxIII_active * FasL_inactive**2.0) / (4.0**2.0 + FasL_inactive**2.0)) + ((2.0 * CxI_active * FasL_inactive**2.0) / (4.0**2.0 + FasL_inactive**2.0)) + ((2.0 * CxII_active * FasL_inactive**2.0) / (4.0**2.0 + FasL_inactive**2.0))) + ((2.0 * FasL_active**2.0) / (4.0**2.0 + FasL_active**2.0))
    dydt[47] = (((2.0 * CxIV_active * FasL_inactive**2.0) / (4.0**2.0 + FasL_inactive**2.0)) + ((2.0 * CYP2E1_active * FasL_inactive**2.0) / (4.0**2.0 + FasL_inactive**2.0)) + ((2.0 * CxIII_active * FasL_inactive**2.0) / (4.0**2.0 + FasL_inactive**2.0)) + ((2.0 * CxI_active * FasL_inactive**2.0) / (4.0**2.0 + FasL_inactive**2.0)) + ((2.0 * CxII_active * FasL_inactive**2.0) / (4.0**2.0 + FasL_inactive**2.0))) - ((2.0 * FasL_active**2.0) / (4.0**2.0 + FasL_active**2.0))

    # GSK3A
    dydt[48]   = -(((2.0 * GSK_3_inactive**2.0) / (4.0**2.0 + GSK_3_inactive**2.0)) * (4.0**2.0 / (4.0**2.0 + Akt_active**2.0))) + ((2.0 * GSK_3_active**2.0) / (4.0**2.0 + GSK_3_active**2.0))
    dydt[49] = (((2.0 * GSK_3_inactive**2.0) / (4.0**2.0 + GSK_3_inactive**2.0)) * (4.0**2.0 / (4.0**2.0 + Akt_active**2.0))) - ((2.0 * GSK_3_active**2.0) / (4.0**2.0 + GSK_3_active**2.0))

    # IKBKB
    dydt[50]   = -(((2.0 * CxIV_active * IKKb_inactive**2.0) / (4.0**2.0 + IKKb_inactive**2.0)) + ((2.0 * TRAF2_active * IKKb_inactive**2.0) / (4.0**2.0 + IKKb_inactive**2.0)) + ((2.0 * CYP2E1_active * IKKb_inactive**2.0) / (4.0**2.0 + IKKb_inactive**2.0)) + ((2.0 * CxIII_active * IKKb_inactive**2.0) / (4.0**2.0 + IKKb_inactive**2.0)) + ((2.0 * CxI_active * IKKb_inactive**2.0) / (4.0**2.0 + IKKb_inactive**2.0)) + ((2.0 * CxII_active * IKKb_inactive**2.0) / (4.0**2.0 + IKKb_inactive**2.0))) + ((2.0 * IKKb_active**2.0) / (4.0**2.0 + IKKb_active**2.0))
    dydt[51] = (((2.0 * CxIV_active * IKKb_inactive**2.0) / (4.0**2.0 + IKKb_inactive**2.0)) + ((2.0 * TRAF2_active * IKKb_inactive**2.0) / (4.0**2.0 + IKKb_inactive**2.0)) + ((2.0 * CYP2E1_active * IKKb_inactive**2.0) / (4.0**2.0 + IKKb_inactive**2.0)) + ((2.0 * CxIII_active * IKKb_inactive**2.0) / (4.0**2.0 + IKKb_inactive**2.0)) + ((2.0 * CxI_active * IKKb_inactive**2.0) / (4.0**2.0 + IKKb_inactive**2.0)) + ((2.0 * CxII_active * IKKb_inactive**2.0) / (4.0**2.0 + IKKb_inactive**2.0))) - ((2.0 * IKKb_active**2.0) / (4.0**2.0 + IKKb_active**2.0))

    # IL1A
    dydt[52]   = -(((2.0 * NF_kB_active * IL_1_inactive**2.0) / (4.0**2.0 + IL_1_inactive**2.0)) + ((2.0 * AP_1_active * IL_1_inactive**2.0) / (4.0**2.0 + IL_1_inactive**2.0))) + ((2.0 * IL_1_active**2.0) / (4.0**2.0 + IL_1_active**2.0))
    dydt[53] = (((2.0 * NF_kB_active * IL_1_inactive**2.0) / (4.0**2.0 + IL_1_inactive**2.0)) + ((2.0 * AP_1_active * IL_1_inactive**2.0) / (4.0**2.0 + IL_1_inactive**2.0))) - ((2.0 * IL_1_active**2.0) / (4.0**2.0 + IL_1_active**2.0))

    # IL6
    dydt[54]   = -(((2.0 * NF_kB_active * IL_6_inactive**2.0) / (4.0**2.0 + IL_6_inactive**2.0)) + ((2.0 * AP_1_active * IL_6_inactive**2.0) / (4.0**2.0 + IL_6_inactive**2.0))) + ((2.0 * IL_6_active**2.0) / (4.0**2.0 + IL_6_active**2.0))
    dydt[55] = (((2.0 * NF_kB_active * IL_6_inactive**2.0) / (4.0**2.0 + IL_6_inactive**2.0)) + ((2.0 * AP_1_active * IL_6_inactive**2.0) / (4.0**2.0 + IL_6_inactive**2.0))) - ((2.0 * IL_6_active**2.0) / (4.0**2.0 + IL_6_active**2.0))

    # IL6R
    dydt[56]   = -(((2.0 * IL_6_active * IL_6R_inactive**2.0) / (4.0**2.0 + IL_6R_inactive**2.0))) + ((2.0 * IL_6R_active**2.0) / (4.0**2.0 + IL_6R_active**2.0))
    dydt[57] = (((2.0 * IL_6_active * IL_6R_inactive**2.0) / (4.0**2.0 + IL_6R_inactive**2.0))) - ((2.0 * IL_6R_active**2.0) / (4.0**2.0 + IL_6R_active**2.0))

    # CXCL8
    dydt[58]   = -(((2.0 * CxIV_active * IL_8_inactive**2.0) / (4.0**2.0 + IL_8_inactive**2.0)) + ((2.0 * CYP2E1_active * IL_8_inactive**2.0) / (4.0**2.0 + IL_8_inactive**2.0)) + ((2.0 * CxIII_active * IL_8_inactive**2.0) / (4.0**2.0 + IL_8_inactive**2.0)) + ((2.0 * CxI_active * IL_8_inactive**2.0) / (4.0**2.0 + IL_8_inactive**2.0)) + ((2.0 * CxII_active * IL_8_inactive**2.0) / (4.0**2.0 + IL_8_inactive**2.0))) + ((2.0 * IL_8_active**2.0) / (4.0**2.0 + IL_8_active**2.0))
    dydt[59] = (((2.0 * CxIV_active * IL_8_inactive**2.0) / (4.0**2.0 + IL_8_inactive**2.0)) + ((2.0 * CYP2E1_active * IL_8_inactive**2.0) / (4.0**2.0 + IL_8_inactive**2.0)) + ((2.0 * CxIII_active * IL_8_inactive**2.0) / (4.0**2.0 + IL_8_inactive**2.0)) + ((2.0 * CxI_active * IL_8_inactive**2.0) / (4.0**2.0 + IL_8_inactive**2.0)) + ((2.0 * CxII_active * IL_8_inactive**2.0) / (4.0**2.0 + IL_8_inactive**2.0))) - ((2.0 * IL_8_active**2.0) / (4.0**2.0 + IL_8_active**2.0))

    # INS
    dydt[60]   = -(((2.0 * GSK_3_active * INS_inactive**2.0) / (4.0**2.0 + INS_inactive**2.0))) + ((2.0 * INS_active**2.0) / (4.0**2.0 + INS_active**2.0))
    dydt[61] = (((2.0 * GSK_3_active * INS_inactive**2.0) / (4.0**2.0 + INS_inactive**2.0))) - ((2.0 * INS_active**2.0) / (4.0**2.0 + INS_active**2.0))

    # INSR
    dydt[62]   = -(((2.0 * INS_active * INSR_inactive**2.0) / (4.0**2.0 + INSR_inactive**2.0))) + ((2.0 * INSR_active**2.0) / (4.0**2.0 + INSR_active**2.0))
    dydt[63] = (((2.0 * INS_active * INSR_inactive**2.0) / (4.0**2.0 + INSR_inactive**2.0))) - ((2.0 * INSR_active**2.0) / (4.0**2.0 + INSR_active**2.0))

    # ERN1
    dydt[64]   = -(((2.0 * IRE1a_inactive**2.0) / (4.0**2.0 + IRE1a_inactive**2.0))) + ((2.0 * IRE1a_active**2.0) / (4.0**2.0 + IRE1a_active**2.0))
    dydt[65] = (((2.0 * IRE1a_inactive**2.0) / (4.0**2.0 + IRE1a_inactive**2.0))) - ((2.0 * IRE1a_active**2.0) / (4.0**2.0 + IRE1a_active**2.0))

    # IRS1
    dydt[66]   = -((((2.0 * INSR_active * IRS_1_2_inactive**2.0) / (4.0**2.0 + IRS_1_2_inactive**2.0))) * (4.0**2.0 / (4.0**2.0 + JNK1_2_active**2.0)) * (4.0**2.0 / (4.0**2.0 + SOCS3_active**2.0))) + ((2.0 * IRS_1_2_active**2.0) / (4.0**2.0 + IRS_1_2_active**2.0))
    dydt[67] = ((((2.0 * INSR_active * IRS_1_2_inactive**2.0) / (4.0**2.0 + IRS_1_2_inactive**2.0))) * (4.0**2.0 / (4.0**2.0 + JNK1_2_active**2.0)) * (4.0**2.0 / (4.0**2.0 + SOCS3_active**2.0))) - ((2.0 * IRS_1_2_active**2.0) / (4.0**2.0 + IRS_1_2_active**2.0))

    # ITCH
    dydt[68]   = -(((2.0 * JNK1_2_active * ITCH_inactive**2.0) / (4.0**2.0 + ITCH_inactive**2.0))) + ((2.0 * ITCH_active**2.0) / (4.0**2.0 + ITCH_active**2.0))
    dydt[69] = (((2.0 * JNK1_2_active * ITCH_inactive**2.0) / (4.0**2.0 + ITCH_inactive**2.0))) - ((2.0 * ITCH_active**2.0) / (4.0**2.0 + ITCH_active**2.0))

    # MAPK8
    dydt[70]   = -(((2.0 * ASK1_active * JNK1_2_inactive**2.0) / (4.0**2.0 + JNK1_2_inactive**2.0)) + ((2.0 * CxIV_active * JNK1_2_inactive**2.0) / (4.0**2.0 + JNK1_2_inactive**2.0)) + ((2.0 * MLK3_active * JNK1_2_inactive**2.0) / (4.0**2.0 + JNK1_2_inactive**2.0)) + ((2.0 * CYP2E1_active * JNK1_2_inactive**2.0) / (4.0**2.0 + JNK1_2_inactive**2.0)) + ((2.0 * CxIII_active * JNK1_2_inactive**2.0) / (4.0**2.0 + JNK1_2_inactive**2.0)) + ((2.0 * CxI_active * JNK1_2_inactive**2.0) / (4.0**2.0 + JNK1_2_inactive**2.0)) + ((2.0 * TNFa_active * JNK1_2_inactive**2.0) / (4.0**2.0 + JNK1_2_inactive**2.0)) + ((2.0 * CxII_active * JNK1_2_inactive**2.0) / (4.0**2.0 + JNK1_2_inactive**2.0))) + ((2.0 * JNK1_2_active**2.0) / (4.0**2.0 + JNK1_2_active**2.0))
    dydt[71] = (((2.0 * ASK1_active * JNK1_2_inactive**2.0) / (4.0**2.0 + JNK1_2_inactive**2.0)) + ((2.0 * CxIV_active * JNK1_2_inactive**2.0) / (4.0**2.0 + JNK1_2_inactive**2.0)) + ((2.0 * MLK3_active * JNK1_2_inactive**2.0) / (4.0**2.0 + JNK1_2_inactive**2.0)) + ((2.0 * CYP2E1_active * JNK1_2_inactive**2.0) / (4.0**2.0 + JNK1_2_inactive**2.0)) + ((2.0 * CxIII_active * JNK1_2_inactive**2.0) / (4.0**2.0 + JNK1_2_inactive**2.0)) + ((2.0 * CxI_active * JNK1_2_inactive**2.0) / (4.0**2.0 + JNK1_2_inactive**2.0)) + ((2.0 * TNFa_active * JNK1_2_inactive**2.0) / (4.0**2.0 + JNK1_2_inactive**2.0)) + ((2.0 * CxII_active * JNK1_2_inactive**2.0) / (4.0**2.0 + JNK1_2_inactive**2.0))) - ((2.0 * JNK1_2_active**2.0) / (4.0**2.0 + JNK1_2_active**2.0))

    # LEP
    dydt[72]   = -(((2.0 * LEP_inactive**2.0) / (4.0**2.0 + LEP_inactive**2.0))) + ((2.0 * LEP_active**2.0) / (4.0**2.0 + LEP_active**2.0))
    dydt[73] = (((2.0 * LEP_inactive**2.0) / (4.0**2.0 + LEP_inactive**2.0))) - ((2.0 * LEP_active**2.0) / (4.0**2.0 + LEP_active**2.0))

    # NR1H3
    dydt[74]   = -(((2.0 * INSR_active * LXR_a_inactive**2.0) / (4.0**2.0 + LXR_a_inactive**2.0))) + ((2.0 * LXR_a_active**2.0) / (4.0**2.0 + LXR_a_active**2.0))
    dydt[75] = (((2.0 * INSR_active * LXR_a_inactive**2.0) / (4.0**2.0 + LXR_a_inactive**2.0))) - ((2.0 * LXR_a_active**2.0) / (4.0**2.0 + LXR_a_active**2.0))

    # PKLR
    dydt[76]   = -(((2.0 * ChREBP_active * L_PK_inactive**2.0) / (4.0**2.0 + L_PK_inactive**2.0))) + ((2.0 * L_PK_active**2.0) / (4.0**2.0 + L_PK_active**2.0))
    dydt[77] = (((2.0 * ChREBP_active * L_PK_inactive**2.0) / (4.0**2.0 + L_PK_inactive**2.0))) - ((2.0 * L_PK_active**2.0) / (4.0**2.0 + L_PK_active**2.0))

    # MAP3K11
    dydt[78]   = -(((2.0 * Rac1_active * MLK3_inactive**2.0) / (4.0**2.0 + MLK3_inactive**2.0)) + ((2.0 * Cdc42_active * MLK3_inactive**2.0) / (4.0**2.0 + MLK3_inactive**2.0))) + ((2.0 * MLK3_active**2.0) / (4.0**2.0 + MLK3_active**2.0))
    dydt[79] = (((2.0 * Rac1_active * MLK3_inactive**2.0) / (4.0**2.0 + MLK3_inactive**2.0)) + ((2.0 * Cdc42_active * MLK3_inactive**2.0) / (4.0**2.0 + MLK3_inactive**2.0))) - ((2.0 * MLK3_active**2.0) / (4.0**2.0 + MLK3_active**2.0))

    # NFKB1
    dydt[80]   = -(((2.0 * IKKb_active * NF_kB_inactive**2.0) / (4.0**2.0 + NF_kB_inactive**2.0)) + ((2.0 * TNFR1_active * NF_kB_inactive**2.0) / (4.0**2.0 + NF_kB_inactive**2.0))) + ((2.0 * NF_kB_active**2.0) / (4.0**2.0 + NF_kB_active**2.0))
    dydt[81] = (((2.0 * IKKb_active * NF_kB_inactive**2.0) / (4.0**2.0 + NF_kB_inactive**2.0)) + ((2.0 * TNFR1_active * NF_kB_inactive**2.0) / (4.0**2.0 + NF_kB_inactive**2.0))) - ((2.0 * NF_kB_active**2.0) / (4.0**2.0 + NF_kB_active**2.0))

    # LEPR
    dydt[82]   = -(((2.0 * LEP_active * ObR_inactive**2.0) / (4.0**2.0 + ObR_inactive**2.0))) + ((2.0 * ObR_active**2.0) / (4.0**2.0 + ObR_active**2.0))
    dydt[83] = (((2.0 * LEP_active * ObR_inactive**2.0) / (4.0**2.0 + ObR_inactive**2.0))) - ((2.0 * ObR_active**2.0) / (4.0**2.0 + ObR_active**2.0))

    # EIF2AK3
    dydt[84]   = -(((2.0 * PERK_inactive**2.0) / (4.0**2.0 + PERK_inactive**2.0))) + ((2.0 * PERK_active**2.0) / (4.0**2.0 + PERK_active**2.0))
    dydt[85] = (((2.0 * PERK_inactive**2.0) / (4.0**2.0 + PERK_inactive**2.0))) - ((2.0 * PERK_active**2.0) / (4.0**2.0 + PERK_active**2.0))

    # P3R3URF-PIK3R3
    dydt[86]   = -(((2.0 * IRS_1_2_active * PI3K_inactive**2.0) / (4.0**2.0 + PI3K_inactive**2.0))) + ((2.0 * PI3K_active**2.0) / (4.0**2.0 + PI3K_active**2.0))
    dydt[87] = (((2.0 * IRS_1_2_active * PI3K_inactive**2.0) / (4.0**2.0 + PI3K_inactive**2.0))) - ((2.0 * PI3K_active**2.0) / (4.0**2.0 + PI3K_active**2.0))

    # PPARA
    dydt[88]   = -(((2.0 * p38_active * PPAR_a_inactive**2.0) / (4.0**2.0 + PPAR_a_inactive**2.0))) + ((2.0 * PPAR_a_active**2.0) / (4.0**2.0 + PPAR_a_active**2.0))
    dydt[89] = (((2.0 * p38_active * PPAR_a_inactive**2.0) / (4.0**2.0 + PPAR_a_inactive**2.0))) - ((2.0 * PPAR_a_active**2.0) / (4.0**2.0 + PPAR_a_active**2.0))

    # PPARG
    dydt[90]   = -(((2.0 * RXR_active * PPAR_g_inactive**2.0) / (4.0**2.0 + PPAR_g_inactive**2.0))) + ((2.0 * PPAR_g_active**2.0) / (4.0**2.0 + PPAR_g_active**2.0))
    dydt[91] = (((2.0 * RXR_active * PPAR_g_inactive**2.0) / (4.0**2.0 + PPAR_g_inactive**2.0))) - ((2.0 * PPAR_g_active**2.0) / (4.0**2.0 + PPAR_g_active**2.0))

    # RXRA
    dydt[92]   = -(((2.0 * LXR_a_active * RXR_inactive**2.0) / (4.0**2.0 + RXR_inactive**2.0))) + ((2.0 * RXR_active**2.0) / (4.0**2.0 + RXR_active**2.0))
    dydt[93] = (((2.0 * LXR_a_active * RXR_inactive**2.0) / (4.0**2.0 + RXR_inactive**2.0))) - ((2.0 * RXR_active**2.0) / (4.0**2.0 + RXR_active**2.0))

    # RAC1
    dydt[94]   = -(((2.0 * Rac1_inactive**2.0) / (4.0**2.0 + Rac1_inactive**2.0))) + ((2.0 * Rac1_active**2.0) / (4.0**2.0 + Rac1_active**2.0))
    dydt[95] = (((2.0 * Rac1_inactive**2.0) / (4.0**2.0 + Rac1_inactive**2.0))) - ((2.0 * Rac1_active**2.0) / (4.0**2.0 + Rac1_active**2.0))

    # SOCS3
    dydt[96]   = -(((2.0 * IL_6R_active * SOCS3_inactive**2.0) / (4.0**2.0 + SOCS3_inactive**2.0))) + ((2.0 * SOCS3_active**2.0) / (4.0**2.0 + SOCS3_active**2.0))
    dydt[97] = (((2.0 * IL_6R_active * SOCS3_inactive**2.0) / (4.0**2.0 + SOCS3_inactive**2.0))) - ((2.0 * SOCS3_active**2.0) / (4.0**2.0 + SOCS3_active**2.0))

    # SREBF1
    dydt[98]   = -(((2.0 * RXR_active * SREBP_1c_inactive**2.0) / (4.0**2.0 + SREBP_1c_inactive**2.0)) + ((2.0 * SOCS3_active * SREBP_1c_inactive**2.0) / (4.0**2.0 + SREBP_1c_inactive**2.0))) + ((2.0 * SREBP_1c_active**2.0) / (4.0**2.0 + SREBP_1c_active**2.0))
    dydt[99] = (((2.0 * RXR_active * SREBP_1c_inactive**2.0) / (4.0**2.0 + SREBP_1c_inactive**2.0)) + ((2.0 * SOCS3_active * SREBP_1c_inactive**2.0) / (4.0**2.0 + SREBP_1c_inactive**2.0))) - ((2.0 * SREBP_1c_active**2.0) / (4.0**2.0 + SREBP_1c_active**2.0))

    # TGFB1
    dydt[100]   = -(((2.0 * CxIV_active * TGF_b1_inactive**2.0) / (4.0**2.0 + TGF_b1_inactive**2.0)) + ((2.0 * CYP2E1_active * TGF_b1_inactive**2.0) / (4.0**2.0 + TGF_b1_inactive**2.0)) + ((2.0 * CxIII_active * TGF_b1_inactive**2.0) / (4.0**2.0 + TGF_b1_inactive**2.0)) + ((2.0 * CxI_active * TGF_b1_inactive**2.0) / (4.0**2.0 + TGF_b1_inactive**2.0)) + ((2.0 * CxII_active * TGF_b1_inactive**2.0) / (4.0**2.0 + TGF_b1_inactive**2.0))) + ((2.0 * TGF_b1_active**2.0) / (4.0**2.0 + TGF_b1_active**2.0))
    dydt[101] = (((2.0 * CxIV_active * TGF_b1_inactive**2.0) / (4.0**2.0 + TGF_b1_inactive**2.0)) + ((2.0 * CYP2E1_active * TGF_b1_inactive**2.0) / (4.0**2.0 + TGF_b1_inactive**2.0)) + ((2.0 * CxIII_active * TGF_b1_inactive**2.0) / (4.0**2.0 + TGF_b1_inactive**2.0)) + ((2.0 * CxI_active * TGF_b1_inactive**2.0) / (4.0**2.0 + TGF_b1_inactive**2.0)) + ((2.0 * CxII_active * TGF_b1_inactive**2.0) / (4.0**2.0 + TGF_b1_inactive**2.0))) - ((2.0 * TGF_b1_active**2.0) / (4.0**2.0 + TGF_b1_active**2.0))

    # TNFRSF1A
    dydt[102]   = -(((2.0 * TNFa_active * TNFR1_inactive**2.0) / (4.0**2.0 + TNFR1_inactive**2.0))) + ((2.0 * TNFR1_active**2.0) / (4.0**2.0 + TNFR1_active**2.0))
    dydt[103] = (((2.0 * TNFa_active * TNFR1_inactive**2.0) / (4.0**2.0 + TNFR1_inactive**2.0))) - ((2.0 * TNFR1_active**2.0) / (4.0**2.0 + TNFR1_active**2.0))

    # TNF
    dydt[104]   = -(((2.0 * NF_kB_active * TNFa_inactive**2.0) / (4.0**2.0 + TNFa_inactive**2.0)) + ((2.0 * AP_1_active * TNFa_inactive**2.0) / (4.0**2.0 + TNFa_inactive**2.0)) + ((2.0 * CxIV_active * TNFa_inactive**2.0) / (4.0**2.0 + TNFa_inactive**2.0)) + ((2.0 * CYP2E1_active * TNFa_inactive**2.0) / (4.0**2.0 + TNFa_inactive**2.0)) + ((2.0 * CxIII_active * TNFa_inactive**2.0) / (4.0**2.0 + TNFa_inactive**2.0)) + ((2.0 * CxI_active * TNFa_inactive**2.0) / (4.0**2.0 + TNFa_inactive**2.0)) + ((2.0 * CxII_active * TNFa_inactive**2.0) / (4.0**2.0 + TNFa_inactive**2.0))) + ((2.0 * TNFa_active**2.0) / (4.0**2.0 + TNFa_active**2.0))
    dydt[105] = (((2.0 * NF_kB_active * TNFa_inactive**2.0) / (4.0**2.0 + TNFa_inactive**2.0)) + ((2.0 * AP_1_active * TNFa_inactive**2.0) / (4.0**2.0 + TNFa_inactive**2.0)) + ((2.0 * CxIV_active * TNFa_inactive**2.0) / (4.0**2.0 + TNFa_inactive**2.0)) + ((2.0 * CYP2E1_active * TNFa_inactive**2.0) / (4.0**2.0 + TNFa_inactive**2.0)) + ((2.0 * CxIII_active * TNFa_inactive**2.0) / (4.0**2.0 + TNFa_inactive**2.0)) + ((2.0 * CxI_active * TNFa_inactive**2.0) / (4.0**2.0 + TNFa_inactive**2.0)) + ((2.0 * CxII_active * TNFa_inactive**2.0) / (4.0**2.0 + TNFa_inactive**2.0))) - ((2.0 * TNFa_active**2.0) / (4.0**2.0 + TNFa_active**2.0))

    # TRAF2
    dydt[106]   = -(((2.0 * IRE1a_active * TRAF2_inactive**2.0) / (4.0**2.0 + TRAF2_inactive**2.0))) + ((2.0 * TRAF2_active**2.0) / (4.0**2.0 + TRAF2_active**2.0))
    dydt[107] = (((2.0 * IRE1a_active * TRAF2_inactive**2.0) / (4.0**2.0 + TRAF2_inactive**2.0))) - ((2.0 * TRAF2_active**2.0) / (4.0**2.0 + TRAF2_active**2.0))

    # XBP1
    dydt[108]   = -(((2.0 * IRE1a_active * XBP1_inactive**2.0) / (4.0**2.0 + XBP1_inactive**2.0))) + ((2.0 * XBP1_active**2.0) / (4.0**2.0 + XBP1_active**2.0))
    dydt[109] = (((2.0 * IRE1a_active * XBP1_inactive**2.0) / (4.0**2.0 + XBP1_inactive**2.0))) - ((2.0 * XBP1_active**2.0) / (4.0**2.0 + XBP1_active**2.0))

    # ADIPOR1
    dydt[110]   = -(((2.0 * ACDC_active * adipoR_inactive**2.0) / (4.0**2.0 + adipoR_inactive**2.0))) + ((2.0 * adipoR_active**2.0) / (4.0**2.0 + adipoR_active**2.0))
    dydt[111] = (((2.0 * ACDC_active * adipoR_inactive**2.0) / (4.0**2.0 + adipoR_inactive**2.0))) - ((2.0 * adipoR_active**2.0) / (4.0**2.0 + adipoR_active**2.0))

    # EIF2S1
    dydt[112]   = -(((2.0 * PERK_active * eIF2a_inactive**2.0) / (4.0**2.0 + eIF2a_inactive**2.0))) + ((2.0 * eIF2a_active**2.0) / (4.0**2.0 + eIF2a_active**2.0))
    dydt[113] = (((2.0 * PERK_active * eIF2a_inactive**2.0) / (4.0**2.0 + eIF2a_inactive**2.0))) - ((2.0 * eIF2a_active**2.0) / (4.0**2.0 + eIF2a_active**2.0))

    # MAPK14
    dydt[114]   = -(((2.0 * AMPK_active * p38_inactive**2.0) / (4.0**2.0 + p38_inactive**2.0))) + ((2.0 * p38_active**2.0) / (4.0**2.0 + p38_active**2.0))
    dydt[115] = (((2.0 * AMPK_active * p38_inactive**2.0) / (4.0**2.0 + p38_inactive**2.0))) - ((2.0 * p38_active**2.0) / (4.0**2.0 + p38_active**2.0))

    # Pathway: P_Adipogenesis
    dydt[116]   = -(((2.0 * C_EBPa_active * P_Adipogenesis_inactive**2.0) / (4.0**2.0 + P_Adipogenesis_inactive**2.0))) + ((2.0 * P_Adipogenesis_active**2.0) / (4.0**2.0 + P_Adipogenesis_active**2.0))
    dydt[117] = (((2.0 * C_EBPa_active * P_Adipogenesis_inactive**2.0) / (4.0**2.0 + P_Adipogenesis_inactive**2.0))) - ((2.0 * P_Adipogenesis_active**2.0) / (4.0**2.0 + P_Adipogenesis_active**2.0))

    # Pathway: P_Apoptosis
    dydt[118]   = -(((2.0 * JNK1_2_active * P_Apoptosis_inactive**2.0) / (4.0**2.0 + P_Apoptosis_inactive**2.0))) + ((2.0 * P_Apoptosis_active**2.0) / (4.0**2.0 + P_Apoptosis_active**2.0))
    dydt[119] = (((2.0 * JNK1_2_active * P_Apoptosis_inactive**2.0) / (4.0**2.0 + P_Apoptosis_inactive**2.0))) - ((2.0 * P_Apoptosis_active**2.0) / (4.0**2.0 + P_Apoptosis_active**2.0))

    # Pathway: P_Cell_death
    dydt[120]   = -(((2.0 * FasL_active * P_Cell_death_inactive**2.0) / (4.0**2.0 + P_Cell_death_inactive**2.0)) + ((2.0 * TNFa_active * P_Cell_death_inactive**2.0) / (4.0**2.0 + P_Cell_death_inactive**2.0))) + ((2.0 * P_Cell_death_active**2.0) / (4.0**2.0 + P_Cell_death_active**2.0))
    dydt[121] = (((2.0 * FasL_active * P_Cell_death_inactive**2.0) / (4.0**2.0 + P_Cell_death_inactive**2.0)) + ((2.0 * TNFa_active * P_Cell_death_inactive**2.0) / (4.0**2.0 + P_Cell_death_inactive**2.0))) - ((2.0 * P_Cell_death_active**2.0) / (4.0**2.0 + P_Cell_death_active**2.0))

    # Pathway: P_De_novo_fatty_acid_synthesis
    dydt[122]   = -(((2.0 * ChREBP_active * P_De_novo_fatty_acid_synthesis_inactive**2.0) / (4.0**2.0 + P_De_novo_fatty_acid_synthesis_inactive**2.0)) + ((2.0 * SREBP_1c_active * P_De_novo_fatty_acid_synthesis_inactive**2.0) / (4.0**2.0 + P_De_novo_fatty_acid_synthesis_inactive**2.0)) + ((2.0 * XBP1_active * P_De_novo_fatty_acid_synthesis_inactive**2.0) / (4.0**2.0 + P_De_novo_fatty_acid_synthesis_inactive**2.0))) + ((2.0 * P_De_novo_fatty_acid_synthesis_active**2.0) / (4.0**2.0 + P_De_novo_fatty_acid_synthesis_active**2.0))
    dydt[123] = (((2.0 * ChREBP_active * P_De_novo_fatty_acid_synthesis_inactive**2.0) / (4.0**2.0 + P_De_novo_fatty_acid_synthesis_inactive**2.0)) + ((2.0 * SREBP_1c_active * P_De_novo_fatty_acid_synthesis_inactive**2.0) / (4.0**2.0 + P_De_novo_fatty_acid_synthesis_inactive**2.0)) + ((2.0 * XBP1_active * P_De_novo_fatty_acid_synthesis_inactive**2.0) / (4.0**2.0 + P_De_novo_fatty_acid_synthesis_inactive**2.0))) - ((2.0 * P_De_novo_fatty_acid_synthesis_active**2.0) / (4.0**2.0 + P_De_novo_fatty_acid_synthesis_active**2.0))

    # Pathway: P_Development_of_NAFLD
    dydt[124]   = -(((2.0 * PPAR_g_active * P_Development_of_NAFLD_inactive**2.0) / (4.0**2.0 + P_Development_of_NAFLD_inactive**2.0))) + ((2.0 * P_Development_of_NAFLD_active**2.0) / (4.0**2.0 + P_Development_of_NAFLD_active**2.0))
    dydt[125] = (((2.0 * PPAR_g_active * P_Development_of_NAFLD_inactive**2.0) / (4.0**2.0 + P_Development_of_NAFLD_inactive**2.0))) - ((2.0 * P_Development_of_NAFLD_active**2.0) / (4.0**2.0 + P_Development_of_NAFLD_active**2.0))

    # Pathway: P_Development_of_steatohepatitis
    dydt[126]   = -(((2.0 * IL_6_active * P_Development_of_steatohepatitis_inactive**2.0) / (4.0**2.0 + P_Development_of_steatohepatitis_inactive**2.0)) + ((2.0 * IL_1_active * P_Development_of_steatohepatitis_inactive**2.0) / (4.0**2.0 + P_Development_of_steatohepatitis_inactive**2.0)) + ((2.0 * TNFa_active * P_Development_of_steatohepatitis_inactive**2.0) / (4.0**2.0 + P_Development_of_steatohepatitis_inactive**2.0))) + ((2.0 * P_Development_of_steatohepatitis_active**2.0) / (4.0**2.0 + P_Development_of_steatohepatitis_active**2.0))
    dydt[127] = (((2.0 * IL_6_active * P_Development_of_steatohepatitis_inactive**2.0) / (4.0**2.0 + P_Development_of_steatohepatitis_inactive**2.0)) + ((2.0 * IL_1_active * P_Development_of_steatohepatitis_inactive**2.0) / (4.0**2.0 + P_Development_of_steatohepatitis_inactive**2.0)) + ((2.0 * TNFa_active * P_Development_of_steatohepatitis_inactive**2.0) / (4.0**2.0 + P_Development_of_steatohepatitis_inactive**2.0))) - ((2.0 * P_Development_of_steatohepatitis_active**2.0) / (4.0**2.0 + P_Development_of_steatohepatitis_active**2.0))

    # Pathway: P_Fibrosis
    dydt[128]   = -(((2.0 * TGF_b1_active * P_Fibrosis_inactive**2.0) / (4.0**2.0 + P_Fibrosis_inactive**2.0))) + ((2.0 * P_Fibrosis_active**2.0) / (4.0**2.0 + P_Fibrosis_active**2.0))
    dydt[129] = (((2.0 * TGF_b1_active * P_Fibrosis_inactive**2.0) / (4.0**2.0 + P_Fibrosis_inactive**2.0))) - ((2.0 * P_Fibrosis_active**2.0) / (4.0**2.0 + P_Fibrosis_active**2.0))

    # Pathway: P_HCC_proliferation
    dydt[130]   = -(((2.0 * JNK1_2_active * P_HCC_proliferation_inactive**2.0) / (4.0**2.0 + P_HCC_proliferation_inactive**2.0))) + ((2.0 * P_HCC_proliferation_active**2.0) / (4.0**2.0 + P_HCC_proliferation_active**2.0))
    dydt[131] = (((2.0 * JNK1_2_active * P_HCC_proliferation_inactive**2.0) / (4.0**2.0 + P_HCC_proliferation_inactive**2.0))) - ((2.0 * P_HCC_proliferation_active**2.0) / (4.0**2.0 + P_HCC_proliferation_active**2.0))

    # Pathway: P_Hepatocyte_injury
    dydt[132]   = -(((2.0 * CASP7_active * P_Hepatocyte_injury_inactive**2.0) / (4.0**2.0 + P_Hepatocyte_injury_inactive**2.0)) + ((2.0 * CASP3_active * P_Hepatocyte_injury_inactive**2.0) / (4.0**2.0 + P_Hepatocyte_injury_inactive**2.0))) + ((2.0 * P_Hepatocyte_injury_active**2.0) / (4.0**2.0 + P_Hepatocyte_injury_active**2.0))
    dydt[133] = (((2.0 * CASP7_active * P_Hepatocyte_injury_inactive**2.0) / (4.0**2.0 + P_Hepatocyte_injury_inactive**2.0)) + ((2.0 * CASP3_active * P_Hepatocyte_injury_inactive**2.0) / (4.0**2.0 + P_Hepatocyte_injury_inactive**2.0))) - ((2.0 * P_Hepatocyte_injury_active**2.0) / (4.0**2.0 + P_Hepatocyte_injury_active**2.0))

    # Pathway: P_Hyperinsulinemia
    dydt[134]   = -(((2.0 * GSK_3_active * P_Hyperinsulinemia_inactive**2.0) / (4.0**2.0 + P_Hyperinsulinemia_inactive**2.0))) + ((2.0 * P_Hyperinsulinemia_active**2.0) / (4.0**2.0 + P_Hyperinsulinemia_active**2.0))
    dydt[135] = (((2.0 * GSK_3_active * P_Hyperinsulinemia_inactive**2.0) / (4.0**2.0 + P_Hyperinsulinemia_inactive**2.0))) - ((2.0 * P_Hyperinsulinemia_active**2.0) / (4.0**2.0 + P_Hyperinsulinemia_active**2.0))

    # Pathway: P_Improvement_of_NAFLD
    dydt[136]   = -(((2.0 * PPAR_a_active * P_Improvement_of_NAFLD_inactive**2.0) / (4.0**2.0 + P_Improvement_of_NAFLD_inactive**2.0)) + ((2.0 * AMPK_active * P_Improvement_of_NAFLD_inactive**2.0) / (4.0**2.0 + P_Improvement_of_NAFLD_inactive**2.0))) + ((2.0 * P_Improvement_of_NAFLD_active**2.0) / (4.0**2.0 + P_Improvement_of_NAFLD_active**2.0))
    dydt[137] = (((2.0 * PPAR_a_active * P_Improvement_of_NAFLD_inactive**2.0) / (4.0**2.0 + P_Improvement_of_NAFLD_inactive**2.0)) + ((2.0 * AMPK_active * P_Improvement_of_NAFLD_inactive**2.0) / (4.0**2.0 + P_Improvement_of_NAFLD_inactive**2.0))) - ((2.0 * P_Improvement_of_NAFLD_active**2.0) / (4.0**2.0 + P_Improvement_of_NAFLD_active**2.0))

    # Pathway: P_Inflammation
    dydt[138]   = -(((2.0 * IL_8_active * P_Inflammation_inactive**2.0) / (4.0**2.0 + P_Inflammation_inactive**2.0)) + ((2.0 * TGF_b1_active * P_Inflammation_inactive**2.0) / (4.0**2.0 + P_Inflammation_inactive**2.0))) + ((2.0 * P_Inflammation_active**2.0) / (4.0**2.0 + P_Inflammation_active**2.0))
    dydt[139] = (((2.0 * IL_8_active * P_Inflammation_inactive**2.0) / (4.0**2.0 + P_Inflammation_inactive**2.0)) + ((2.0 * TGF_b1_active * P_Inflammation_inactive**2.0) / (4.0**2.0 + P_Inflammation_inactive**2.0))) - ((2.0 * P_Inflammation_active**2.0) / (4.0**2.0 + P_Inflammation_active**2.0))

    return dydt


def simulate(t_max=200, n_points=2001, y0=None, params=None):
    """Run ODE simulation. Returns (t, y)."""
    if y0 is None:     y0     = Y0
    if params is None: params = PARAMS
    t = np.linspace(0, t_max, n_points)
    y = odeint(ode_system, y0, t, args=(params,), mxstep=10000)
    return t, y


def get_pathway_steady_states(y, last_frac=0.1):
    """Return {var_name: steady_state_value} for all active pathway variables."""
    n = max(1, int(len(y) * last_frac))
    return {STATE_VARS[i]: float(np.mean(y[-n:, i]))
             for i in range(len(STATE_VARS))
             if '_active' in STATE_VARS[i] and
                STATE_VARS[i].replace('_active', '') in PATHWAY_METADATA}


def get_gene_steady_states(y, last_frac=0.1):
    """Return {gene_symbol: (inactive_ss, active_ss)}."""
    n = max(1, int(len(y) * last_frac))
    result = {}
    for g, meta in GENE_METADATA.items():
        sym = meta.get('symbol', g)
        try:
            i_in  = STATE_VARS.index(g + '_inactive')
            i_act = STATE_VARS.index(g + '_active')
            result[sym] = (float(np.mean(y[-n:, i_in])),
                           float(np.mean(y[-n:, i_act])))
        except ValueError:
            pass
    return result


def get_pathway_timeseries(y):
    """Return {pathway_name: active_curve} for all pathway output nodes."""
    result = {}
    for pw, meta in PATHWAY_METADATA.items():
        pname = meta.get('pathway_name', pw)
        try:
            i = STATE_VARS.index(pw + '_active')
            result[pname] = y[:, i]
        except ValueError:
            pass
    return result


if __name__ == "__main__":
    print("Model Info:", MODEL_INFO)
    print(f"Genes: {len(GENE_METADATA)} | Pathways: {len(PATHWAY_METADATA)}")
    t, y = simulate()
    ss = get_pathway_steady_states(y)
    print("Pathway steady states (active):")
    for k, v in sorted(ss.items()):
        print(f"  {k}: {v:.4f}")
